name: "🐞 バグ"
description: "バグの報告"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: context
    attributes:
      label: 内容
      description: 発生箇所 / 機能、現象、再現手順など
      value: |
        ## 発生箇所/機能
        - ex. ブログ詳細, ブログプレビュー

        ## 現象
        - ex. プレビューが表示されない

        ## 再現手順
        - ex. 1. ブログ詳細ページに遷移
            2. 「下書きに戻して編集」を押下
            3. 「プレビュー」ボタンを押下

        ## 確認環境
        - ex. ブラウザ: Chrome 127 / Safari 17.5
        - ex. OS: macOS 14.5 / iOS 17.5
        - ex. 画面幅: 390px / 1440px

        ## 期待する動作
        - ex. プレビュー画面が表示される
    validations:
      required: true
