name: "🐞 バグ報告"
description: "バグを報告する"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: context
    attributes:
      label: 概要
      description: 発生箇所/機能、バグ内容などを簡潔に記載してください
      placeholder: |
        - 発生箇所
          - ブログ詳細 / ブログプレビュー
        - 現象
          - プレビューが表示されない
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      placeholder: |
        1. ブログ詳細ページに遷移
        2. 「下書きに戻して編集」を押下
        3. 「プレビュー」ボタンを押下
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
      placeholder: |
        - プレビュー画面が表示される
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: 確認環境
      description: 再現を確認した環境を1つ以上記載してください
      placeholder: |
        ブラウザ: Chrome 127 / Safari 17.5
        OS: macOS 14.5 / iOS 17.5
        画面幅: 390px / 1440px
    validations:
      required: false
