name: "🐞 バグ"
description: "バグの報告"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: context
    attributes:
      label: 内容
      description: 発生箇所/機能、現象、再現手順など
      value: |
        ## 発生箇所/機能
        ## 現象
        ## 再現手順
        ## 期待する動作
        ## 確認環境
    validations:
      required: true
